version: "3"

services:
  osticket:
    build: .
    image: jrcichra/osticket
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=osticket
      - MYSQL_USER=osticket
      - MYSQL_PASSWORD=0T1cket

      # CHANGE ME
      - INSTALL_SECRET=secret

      - LANGUAGE=fa

    links:
      - mysql:mysql
    ports:
      - "5335:80"
    restart: always

  mysql:
    image: ghcr.io/linuxserver/mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=osticket
      - MYSQL_USER=osticket
      - MYSQL_PASSWORD=0T1cket
    restart: always
